# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-14 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_tipovestidomanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendetuvestido',
            name='medida_cadera',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendetuvestido',
            name='medida_cintura',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
